version: "1.0"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
